// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson89aae3efDecodeOzoneInternal(in *jlexer.Lexer, out *Peoples) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson89aae3efEncodeOzoneInternal(out *jwriter.Writer, in Peoples) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Peoples) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson89aae3efEncodeOzoneInternal(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Peoples) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson89aae3efDecodeOzoneInternal(l, v)
}
func easyjson89aae3efDecodeOzoneInternal1(in *jlexer.Lexer, out *People) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson89aae3efEncodeOzoneInternal1(out *jwriter.Writer, in People) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v People) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson89aae3efEncodeOzoneInternal1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *People) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson89aae3efDecodeOzoneInternal1(l, v)
}
